services:
  app:
    build: .
    container_name: srecajmose-app
    env_file:
      - .env
    command: node server.js
    ports:
      - "3000:3000"
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - NODE_ENV=docker
    # Za development mode z nodemon odkomentiraj spodnje:
    # volumes:
    #   - .:/usr/src/app
    #   - /usr/src/app/node_modules
    #   - /usr/src/app/angular/build
    # command: sh -c "npm install && npm run dev"
  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: always
    env_file:
      - .env
    ports:
      - "27018:27017" # 27018 je da maste loceno dostop prek kompasa ker ponavadi je lokalna baza na loalhost:27017
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  mongo-data:
  node_modules: